<?php

namespace Database\Seeders;

use App\Models\Faq;
use Illuminate\Database\Seeder;

class FaqSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (Faq::count() == 0) {
            Faq::insert([
                [
                    'title' => 'CAN I SET UP A PAYMENT PLAN?',
                    'description' => '<p>Yes! You can structure your payments in one of 3 ways after making a deposit:</p><ul><li>Let the balance charge automatically on the balance due date.</li><li>Set up a monthly auto draft by emailing&nbsp;<a href="mailto:'.config('emails.groups').'" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 0, 0);"><strong>'.config('emails.groups').'</strong></a>.</li><li>Make payments on your own schedule at any time with the "Make a Payment" button below.</li></ul>',
                    'type' => 'static',
                ],
                [
                    'title' => 'WHAT IS THE CANCELLATION POLICY?',
                    'description' => 'The description for this FAQ is generated by the system in real time. If you want to make changes to this FAQ, please contact the developers. Or you can simply remove it from the couples website.',
                    'type' => 'static',
                ],
                [
                    'title' => 'WILL I NEED A PASSPORT?',
                    'description' => '<p><span style="color: rgb(10, 10, 10);">Yes! A passport is needed to fly anywhere internationally - please take the time now to locate your passport and check the expiration date; make sure it is valid for 6 months after your anticipated return date. Check this site for more passport info:&nbsp;</span><a href="https://travel.state.gov/content/travel/en/passports.html" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 0, 0);"><strong>https://travel.state.gov/content/passports/en/passports</strong></a></p>',
                    'type' => 'static',
                ],
                [
                    'title' => 'IS TRAVEL INSURANCE AVAILABLE?',
                    'description' => 'The description for this FAQ is generated by the system in real time. If you want to make changes to this FAQ, please contact the developers. Or you can simply remove it from the couples website.',
                    'type' => 'dynamic',
                ],
            ]);
        }
    }
}
